# Generated by Django 2.1.5 on 2019-09-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaNew',
            fields=[
                ('Id', models.AutoField(db_column='AreaID', primary_key=True, serialize=False)),
                ('Name', models.CharField(db_column='AreaName', max_length=100)),
            ],
            options={
                'db_table': 'AreaNew',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('Name', models.CharField(db_column='Name', max_length=50)),
            ],
            options={
                'db_table': 'Status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('TechnicianID', models.AutoField(db_column='TechnicianID', primary_key=True, serialize=False)),
                ('TechnicianName', models.CharField(db_column='TechnicianName', max_length=50)),
                ('Designation', models.CharField(db_column='Designation', max_length=100)),
                ('StaffID', models.CharField(db_column='StaffID', max_length=100)),
                ('MobileNo', models.CharField(db_column='MobileNo', max_length=100)),
                ('BloodGroup', models.CharField(db_column='BloodGroup', max_length=100)),
                ('TerritoryCode', models.CharField(db_column='TerritoryCode', max_length=100)),
                ('Notes', models.CharField(db_column='Notes', max_length=100)),
                ('SupervisorCode', models.CharField(db_column='SupervisorCode', max_length=100)),
            ],
            options={
                'db_table': 'Technician',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TerritoryNew',
            fields=[
                ('TerritoryID', models.AutoField(db_column='TerritoryID', primary_key=True, serialize=False)),
                ('TerritoryCode', models.CharField(db_column='TerritoryCode', max_length=50)),
                ('TerritoryName', models.CharField(db_column='TerritoryName', max_length=100)),
                ('AreaID', models.CharField(db_column='AreaID', max_length=100)),
                ('Notes', models.CharField(db_column='Notes', max_length=100)),
            ],
            options={
                'db_table': 'TerritoryNew',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserManager',
            fields=[
                ('UserID', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('UserName', models.CharField(db_column='UserName', max_length=255, unique=True)),
                ('Password', models.CharField(db_column='Password', max_length=255)),
                ('DisplayName', models.CharField(db_column='DisplayName', max_length=100)),
            ],
            options={
                'db_table': 'UserManager',
                'managed': False,
            },
        ),
    ]
