# Generated by Django 2.1.8 on 2019-09-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotorServicesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='Notes',
            field=models.CharField(db_column='Notes', default='', max_length=100),
        ),
    ]
